version: '3.8'

services:
  db:
    container_name: rent-car-postgres
    image: postgres:14.0-alpine
    restart: always
    environment:
      - POSTGRES_USER=${PG_USERNAME}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DATABASE}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - ${PG_PORT}:${PG_PORT}
  backend:
    container_name: rent-car-backend
    build:
      context: ./backend
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - '${API_PORT}:${API_PORT}'
    environment:
      - API_PORT=${API_PORT}
      - API_HOST=${API_HOST}
      - TYPEORM_CONNECTION=${PG_CONNECTION}
      - TYPEORM_USERNAME=${PG_USERNAME}
      - TYPEORM_PASSWORD=${PG_PASSWORD}
      - TYPEORM_DATABASE=${PG_DATABASE}
      - TYPEORM_PORT=${PG_PORT}
      - TYPEORM_HOST=db
